export const SuggestionConstants = {
    CREATESUGGESTION_REQUEST:'CREATESUGGESTION_REQUEST',
    CREATESUGGESTION_SUCCESS:'CREATESUGGESTION_SUCCESS',
    CREATESUGGESTION_FAIL:'CREATESUGGESTION_FAIL',

    GETSUGGESTIONS_REQUEST:'GETSUGGESTIONS_REQUEST',
    GETSUGGESTIONS_SUCCESS:'GETSUGGESTIONS_SUCCESS',
    GETSUGGESTIONS_FAIL:'GETSUGGESTIONS_FAIL',

    CLEARSUGGESTIONS_REQUEST:'CLEARSUGGESTIONS_REQUEST',

    SIGNSUGGESTION_REQUEST:'SIGNSUGGESTION_REQUEST',
    SIGNSUGGESTION_SUCCESS:'SIGNSUGGESTION_SUCCESS',
    SIGNSUGGESTION_FAIL:'SIGNSUGGESTION_FAIL',

    ADDSUGGESTION_SSE:'ADDSUGGESTION_SSE',
    PROCESSSIGNATURE_SSE:'PROCESSSIGNATURE_SSE'
}