export const SuggestionConstants = {
    CREATESUGGESTION_REQUEST:'CREATESUGGESTION_REQUEST',
    CREATESUGGESTION_SUCCESS:'CREATESUGGESTION_SUCCESS',
    CREATESUGGESTION_FAIL:'CREATESUGGESTION_FAIL',

    GETSUGGESTIONS_REQUEST:'GETSUGGESTIONS_REQUEST',
    GETSUGGESTIONS_SUCCESS:'GETSUGGESTIONS_SUCCESS',
    GETSUGGESTIONS_FAIL:'GETSUGGESTIONS_FAIL',

    CLEARSUGGESTIONS_REQUEST:'CLEARSUGGESTIONS_REQUEST',

    ADDSUGGESTION_SSE:'ADDSUGGESTION_SSE',
}